# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='ccv',
            new_name='ccv_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
